version: "3.9"

networks:
  net:
    driver: overlay

x-labels: &def-labels
  app.part-off: ${VENDOR}
  app.version: ${VERSION}

x-logging: &def-logging
  options: 
    max-size: ${LOG_MAX_SIZE}
    max-file: ${LOG_MAX_FILE}

x-limits: &def-limits
  limits:
    cpus: '16'
    memory: 3GB
    
services:
  ebs-proxy:
    image: ${REGISTRY_URl}/${VENDOR}/${PROXY_IMAGE}:${PROXY_TAG}
    environment:
      - PATH_PREFIX=${PATH_PREFIX}
      - WORKERS=${WORKERS}
      - IDRND_BASE_URL=http://engine:8080
    logging: *def-logging
    labels: *def-labels
    ports:
      - ${PUBLISH_PORT}:5000
    deploy:
      resources: *def-limits
      placement:
        max_replicas_per_node: ${MAX_REPL_PER_NODE_FOR_PROXY}
      mode: replicated
      replicas: ${PROXY_COUNT}
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
          test: "curl --fail http://localhost:5000/v1/${PATH_PREFIX}/liveness/healthcheck || exit 1"
          interval: 60s
          retries: 3
          start_period: 10s
          timeout: 5s
    networks:
      - net

  engine:
    image: ${REGISTRY_URl}/${VENDOR}/${ENGINE_IMAGE}:${ENGINE_TAG}
    logging: *def-logging
    labels: *def-labels
    deploy:
      resources: *def-limits
      placement:
        max_replicas_per_node: ${REPL_PER_NODE}
      mode: replicated
      replicas: ${CORE_COUNT}
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
          test: "curl --fail http://localhost:8080/core/get_build_info || exit 1"
          interval: 60s
          retries: 3
          start_period: 10s
          timeout: 5s
    networks:
      - net
